### ISSUE TITLE
Unnecessary Import

### ISSUE THREAD

**Issue by driskerr** [tepope/pwp-capstones#2]
https://github.com/tepope/pwp-capstones/blob/db513fbba8368c0080624547846a0dac57295c0e/capstone/GDP%20and%20Life%20Expectancy%20Capstone%20Final.py#L35

Good thinking - but you never made use of `pylab` :/ If you're not going to use a library, you don't need to import it ¯\\_(ツ)_/¯

**Comment by tepope** [comment]
#doh!

I was trying some calculation of the axis labels and decided to remove it...forgot to remove the import. 

¯\_(ツ)_/¯
